apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-backend
spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-frontend
spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "200m"
              memory: "128Mi"