apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: backend-deploy-patch.yaml
  - path: frontend-deploy-patch.yaml

images:
  - name: surya0610/api
    newTag: sha-04a26619769e6cf01bfc0c049be322be779066a3

  - name: surya0610/client
    newTag: sha-04a26619769e6cf01bfc0c049be322be779066a3