apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: backend-deploy-patch.yaml
  - path: frontend-deploy-patch.yaml

images:
  - name: surya0610/api
    newTag: sha-abc123

  - name: surya0610/client
    newTag: sha-abc123